# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configDB.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(280, 300)
        Form.setMinimumSize(QtCore.QSize(280, 300))
        Form.setMaximumSize(QtCore.QSize(280, 300))
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.userName = QtWidgets.QLineEdit(Form)
        self.userName.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.userName.setFont(font)
        self.userName.setObjectName("userName")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.userName)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.password)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.databaseName = QtWidgets.QLineEdit(Form)
        self.databaseName.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.databaseName.setFont(font)
        self.databaseName.setObjectName("databaseName")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.databaseName)
        self.serverHost = QtWidgets.QLineEdit(Form)
        self.serverHost.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.serverHost.setFont(font)
        self.serverHost.setObjectName("serverHost")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.serverHost)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.dbCheck_btn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dbCheck_btn.setFont(font)
        self.dbCheck_btn.setObjectName("dbCheck_btn")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.dbCheck_btn)
        self.status_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.status_label.setFont(font)
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.status_label)
        self.save_btn = QtWidgets.QPushButton(Form)
        self.save_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.save_btn.setFont(font)
        self.save_btn.setObjectName("save_btn")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.save_btn)
        self.save_label = QtWidgets.QLabel(Form)
        self.save_label.setText("")
        self.save_label.setObjectName("save_label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.save_label)
        self.Exit_btn = QtWidgets.QPushButton(Form)
        self.Exit_btn.setObjectName("Exit_btn")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.Exit_btn)
        self.gridLayout_3.addLayout(self.formLayout, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Server User"))
        self.label_4.setText(_translate("Form", "Password"))
        self.label_5.setText(_translate("Form", "Database Name"))
        self.label_2.setText(_translate("Form", "Server Host"))
        self.dbCheck_btn.setText(_translate("Form", "Connection Check"))
        self.save_btn.setText(_translate("Form", "Save"))
        self.Exit_btn.setText(_translate("Form", "Exit"))
